---
- name: variable example
  hosts: all
  vars: 
   URL: "Global variable"
  tasks: 
  - name: print global variable
    debug:
     msg: "{{URL}}"  
  - name: print local variable
    vars:
     url: "Local Variable"
    debug:
     msg: "{{url}}"
  - name:
    debug:
     msg: "{{URL}}"
...
