---
- name: install multiple packages
  hosts: all
  become: True
  tasks:
   - name: install multiple packages
     yum:
      name: "{{item}}"
      state: latest
     loop:
       - vim
       - wget
       - git
       - tree
...